/**
 * Shared constants for the Macros Plugin
 */

export const MACRO_TYPES = {
  PROTEIN: 'protein',
  FAT: 'fat',
  CARBS: 'carbs',
  CALORIES: 'calories',
} as const;

export const CLASS_NAMES = {
  TABLE: {
    CONTAINER: 'macros-table',
    HEADER: 'macros-table-header',
    INFO: 'macros-table-info',
    ID_LABEL: 'macros-table-id-label',
    ID: 'macros-table-id',
    CONTROLS: 'macros-table-controls',
    CONTROL_ICON: 'macros-control-icon',
    COLUMN_HEADER: 'column-header',
    MEAL_HEADER: 'meal-header',
    MEAL_HEADER_CELL: 'meal-header-cell',
    MEAL_HEADER_CONTENT: 'meal-header-content',
    MEAL_NAME: 'meal-name',
    MEAL_CALORIE_SUMMARY: 'meal-calorie-summary',
    MEAL_TOGGLE_ICON: 'meal-toggle-icon',
    TOTALS_ROW: 'totals-row',
    TARGETS_ROW: 'targets-row',
    REMAINING_ROW: 'remaining-row',
    COLLAPSIBLE: 'collapsible',
    COLLAPSED: 'collapsed',
    HIDDEN: 'hidden',
    EXCEEDED: 'exceeded',
  },
  MACRO: {
    CELL: 'macro-cell',
    PERCENTAGE: 'macro-percentage',
    TOOLTIP: 'macro-tooltip',
    PROTEIN_CELL: 'protein-cell',
    FAT_CELL: 'fat-cell',
    CARBS_CELL: 'carbs-cell',
    CALORIES_CELL: 'calories-cell',
  },
  PROGRESS: {
    CONTAINER: 'macro-progress-container',
    BAR: 'macro-progress-bar',
    TARGET_CONTAINER: 'target-progress-container',
    TARGET_BAR: 'target-bar',
    PROTEIN_PROGRESS: 'protein-progress',
    FAT_PROGRESS: 'fat-progress',
    CARBS_PROGRESS: 'carbs-progress',
    CALORIES_PROGRESS: 'calories-progress',
    MICRO_VALUE: 'micro-value',
    UNDER_TARGET: 'under-target',
    OVER_TARGET: 'over-target',
    NEAR_TARGET: 'near-target',
  },
  DASHBOARD: {
    CONTAINER: 'macro-dashboard',
    HEADER: 'macro-dashboard-header',
    CONTENT: 'macro-dashboard-content',
    METRIC_CARD: 'macro-metric-card',
    METRIC_LABEL: 'macro-metric-label',
    METRIC_VALUE_CONTAINER: 'macro-metric-value-container',
    METRIC_VALUE: 'macro-metric-value',
    METRIC_PERCENTAGE: 'macro-metric-percentage',
    METRIC_PROGRESS_CONTAINER: 'macro-metric-progress-container',
    METRIC_PROGRESS_BAR: 'macro-metric-progress-bar',
    METRIC_TARGET_INDICATOR: 'macro-metric-target-indicator',
  },
  ICONS: {
    ADD: 'add-icon',
    REMOVE: 'remove-icon',
    COLLAPSE_ALL: 'collapse-all-icon',
    EXPAND_ALL: 'expand-all-icon',
  },
} as const;
